name: CDVAEycy38
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_0
  - pip=23.2.1=py38h06a4308_0
  - python=3.8.17=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - altair==5.0.1
    - antlr4-python3-runtime==4.9.3
    - anyio==3.7.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - ase==3.22.1
    - astroid==2.15.6
    - asttokens==2.2.1
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - autopep8==2.0.2
    - babel==2.12.1
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - blinker==1.6.2
    - cachetools==5.3.1
    - certifi==2023.7.22
    - cffi==1.15.1
    - charset-normalizer==3.2.0
    - click==8.1.6
    - cmake==3.25.0
    - comm==0.1.4
    - contourpy==1.1.0
    - cycler==0.11.0
    - debugpy==1.6.7.post1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.7
    - dnspython==2.4.2
    - emmet-core==0.64.3
    - et-xmlfile==1.1.0
    - exceptiongroup==1.1.2
    - executing==1.2.0
    - fastjsonschema==2.18.0
    - filelock==3.9.0
    - fire==0.5.0
    - fonttools==4.42.0
    - fqdn==1.5.1
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.32
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.57.0
    - hydra-core==1.3.2
    - hydra-joblib-launcher==1.2.0
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.1
    - iniconfig==2.0.0
    - ipykernel==6.25.1
    - ipython==8.12.2
    - ipywidgets==8.1.0
    - isoduration==20.11.0
    - isort==5.12.0
    - jedi==0.19.0
    - jinja2==3.1.2
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.19.0
    - jsonschema-specifications==2023.7.1
    - jupyter-client==8.3.0
    - jupyter-core==5.3.1
    - jupyter-events==0.7.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.7.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.24.0
    - jupyterlab-widgets==3.0.8
    - kiwisolver==1.4.4
    - latexcodec==2.0.1
    - lazy-object-proxy==1.9.0
    - lightning-lite==1.8.0
    - lightning-utilities==0.3.0
    - lit==15.0.7
    - markdown==3.4.4
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matminer==0.9.0
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - mdurl==0.1.2
    - mistune==3.0.1
    - monty==2023.8.8
    - mp-api==0.33.3
    - mpmath==1.3.0
    - msgpack==1.0.5
    - multidict==6.0.4
    - multiprocess==0.70.15
    - nbclient==0.8.0
    - nbconvert==7.7.3
    - nbformat==5.9.2
    - nest-asyncio==1.5.7
    - networkx==3.1
    - nglview==3.0.6
    - notebook-shim==0.2.3
    - numpy==1.24.4
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - openpyxl==3.1.2
    - overrides==7.4.0
    - p-tqdm==1.4.0
    - packaging==23.1
    - palettable==3.3.3
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathos==0.3.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.10.0
    - plotly==5.16.0
    - pluggy==1.2.0
    - pox==0.3.3
    - ppft==1.7.6.7
    - prometheus-client==0.17.1
    - prompt-toolkit==3.0.39
    - protobuf==4.24.0
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==12.0.1
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pybtex==0.24.0
    - pycodestyle==2.11.0
    - pycparser==2.21
    - pydantic==1.10.12
    - pydeck==0.8.0
    - pyg-lib==0.2.0+pt20cu118
    - pygments==2.16.1
    - pylint==2.17.5
    - pymatgen==2023.8.10
    - pymongo==4.4.1
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pytest==7.4.0
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - python-json-logger==2.0.7
    - pytorch-lightning==1.8.0
    - pytz==2023.3
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - referencing==0.30.2
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.5.2
    - rpds-py==0.9.2
    - rsa==4.9
    - ruamel-yaml==0.17.32
    - ruamel-yaml-clib==0.2.7
    - scikit-learn==1.3.0
    - scipy==1.10.1
    - seaborn==0.12.2
    - send2trash==1.8.2
    - six==1.16.0
    - smact==2.5.2
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - spglib==2.0.2
    - stack-data==0.6.2
    - streamlit==1.25.0
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==8.2.2
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.1
    - termcolor==2.3.0
    - terminado==0.17.1
    - threadpoolctl==3.2.0
    - tinycss2==1.2.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.12.1
    - toolz==0.12.0
    - torch==2.0.1+cu118
    - torch-cluster==1.6.1+pt20cu118
    - torch-geometric==2.3.1
    - torch-scatter==2.1.1+pt20cu118
    - torch-sparse==0.6.17+pt20cu118
    - torch-spline-conv==1.2.2+pt20cu118
    - torchaudio==2.0.2+cu118
    - torchmetrics==0.11.4
    - torchvision==0.15.2+cu118
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.9.0
    - triton==2.0.0
    - typing-extensions==4.7.1
    - tzdata==2023.3
    - tzlocal==4.3.1
    - uncertainties==3.1.7
    - uri-template==1.3.0
    - urllib3==1.26.16
    - validators==0.21.2
    - watchdog==3.0.0
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.1
    - werkzeug==2.3.6
    - widgetsnbextension==4.0.8
    - wrapt==1.15.0
    - yarl==1.9.2
    - zipp==3.16.2
prefix: /home/cyye/anaconda3/envs/CDVAEycy38
